// Generated by CoffeeScript 1.11.1
(function() {
  var PNG, RSVP, fs;

  fs = require('fs');

  PNG = require('pngjs').PNG;

  RSVP = require('rsvp');

  module.exports = {
    toPng: function() {
      var png;
      png = new PNG({
        filterType: 4,
        width: this.width(),
        height: this.height()
      });
      png.data = this.pixelData;
      return png;
    },
    saveAsPng: function(output) {
      return new RSVP.Promise((function(_this) {
        return function(resolve, reject) {
          return _this.toPng().pack().pipe(fs.createWriteStream(output)).on('finish', resolve);
        };
      })(this));
    }
  };

}).call(this);
